# Generated by Django 3.2.5 on 2021-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=17)),
                ('Email', models.EmailField(max_length=254)),
                ('NID', models.CharField(max_length=25)),
                ('Present_Adress', models.TextField()),
                ('Permanent_Adress', models.TextField()),
                ('Available', models.BooleanField()),
                ('Details', models.TextField()),
                ('Image', models.ImageField(default='default.jpg', upload_to='media/image')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
