# Generated by Django 3.2.5 on 2021-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Nures', 'Nures'), ('Work_maid', 'Work_maid')], default=1, max_length=100),
        ),
    ]
