# Generated by Django 3.2.5 on 2021-08-01 10:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20210731_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Arabir', 'Arabic')], default='Bangla', max_length=100),
        ),
    ]
